// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHvQ9lvc50FmOvBVIOJELOuSVikggrcM',
    appId: '1:700778693716:web:84945470cec72d00db59c1',
    messagingSenderId: '700778693716',
    projectId: 'tft-synk',
    authDomain: 'tft-synk.firebaseapp.com',
    storageBucket: 'tft-synk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6mVT-SZjwG1vJzCrJ8QSoBGgGiKXlmRo',
    appId: '1:700778693716:android:3b42bd9bdb0cdf1fdb59c1',
    messagingSenderId: '700778693716',
    projectId: 'tft-synk',
    storageBucket: 'tft-synk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgE19waBCaFmvlv9D9Pb79c2akPL4XN-A',
    appId: '1:700778693716:ios:e45ff06b9b37e6f5db59c1',
    messagingSenderId: '700778693716',
    projectId: 'tft-synk',
    storageBucket: 'tft-synk.appspot.com',
    iosBundleId: 'com.example.tftSynk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgE19waBCaFmvlv9D9Pb79c2akPL4XN-A',
    appId: '1:700778693716:ios:e45ff06b9b37e6f5db59c1',
    messagingSenderId: '700778693716',
    projectId: 'tft-synk',
    storageBucket: 'tft-synk.appspot.com',
    iosBundleId: 'com.example.tftSynk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHvQ9lvc50FmOvBVIOJELOuSVikggrcM',
    appId: '1:700778693716:web:19266b9303293981db59c1',
    messagingSenderId: '700778693716',
    projectId: 'tft-synk',
    authDomain: 'tft-synk.firebaseapp.com',
    storageBucket: 'tft-synk.appspot.com',
  );
}
